test_that("write_oxcal() writes file to specified path", {
  cql_obj <- cql(cql_date("test", 1000))
  tmp <- tempfile(fileext = ".oxcal")
  on.exit(unlink(tmp))

  result <- write_oxcal(cql_obj, tmp)

  expect_true(file.exists(tmp))
})

test_that("write_oxcal() auto-appends .oxcal extension", {
  cql_obj <- cql(cql_date("test", 1000))
  tmp <- tempfile()
  expected_path <- paste0(tmp, ".oxcal")
  on.exit(unlink(expected_path))

  expect_message(
    write_oxcal(cql_obj, tmp),
    "Writing to"
  )
  expect_true(file.exists(expected_path))
})

test_that("write_oxcal() returns cql object invisibly", {
  cql_obj <- cql(cql_date("test", 1000))
  tmp <- tempfile(fileext = ".oxcal")
  on.exit(unlink(tmp))

  result <- write_oxcal(cql_obj, tmp)

  expect_s3_class(result, "cql")
  expect_identical(result, cql_obj)
})

test_that("write_oxcal() writes correct content", {
  cql_obj <- cql(cql_date("test", 1000))
  tmp <- tempfile(fileext = ".oxcal")
  on.exit(unlink(tmp))

  write_oxcal(cql_obj, tmp)
  content <- readLines(tmp)

  expect_true(any(grepl("CQL2 generated by stratigraphr", content)))
  expect_true(any(grepl("Date\\(\"test\", 1000\\)", content)))
})

test_that("write_oxcal() uses \\r\\n line endings", {
  cql_obj <- cql(cql_date("test", 1000))
  tmp <- tempfile(fileext = ".oxcal")
  on.exit(unlink(tmp))

  write_oxcal(cql_obj, tmp)
  raw_content <- readBin(tmp, "raw", file.info(tmp)$size)

  expect_true(any(raw_content == as.raw(0x0d)))
})

test_that("write_oxcal() errors on non-cql input", {
  tmp <- tempfile(fileext = ".oxcal")
  on.exit(unlink(tmp))

  expect_error(write_oxcal("not a cql object", tmp))
  expect_error(write_oxcal(list(a = 1), tmp))
})

test_that("write_oxcal() handles empty cql object", {
  cql_obj <- cql()
  tmp <- tempfile(fileext = ".oxcal")
  on.exit(unlink(tmp))

  expect_no_error(write_oxcal(cql_obj, tmp))
  expect_true(file.exists(tmp))
})
