# API for OxCal's Chronological Query Language (CQL2)
# See https://c14.arch.ox.ac.uk/oxcalhelp/hlp_commands.html

# TODO:
# * Default names – or at least a warning if name is forgotten
# * Indenting
# * More sophisticated type checking:
#   * Expressions in e.g. Boundary() can only take a limited number of other
#     commands
# * How to handle lists passed to functions with ...? (e.g. in a dplyr chain)

#' Chronological Query Language (CQL)
#'
#' Provides an R API for the Chronological Query Language (CQL), primarily used
#' to input commands and describe models to OxCal.
#'
#' @return `cql`. A CQL script.
#'
#' @references
#' <https://c14.arch.ox.ac.uk/oxcalhelp/hlp_commands.html>
#'
#' @export
cql <- function(...) {
  cql <- paste(..., sep = "\n", collapse = "\n")
  class(cql) <- c("cql", class(cql))
  return(cql)
}


# cql class methods (printing etc.) ---------------------------------------
#' @export
print.cql <- function(cql) {
  cql <- paste0("// CQL2 generated by stratigraphr v",
                utils::packageVersion("stratigraphr"),
                "\n",
                cql)
  writeLines(cql)
}

assert_cql_dots <- function(...) {
  purrr::map(list(...),
             checkmate::assert_class,
             classes= "cql",
             .var.name = "...")
}


# Read/write functions ----------------------------------------------------

#' Write CQL to a file
#'
#' Writes CQL code from [cql()] to an .oxcal file, for input to OxCal.
#'
#' @param cql   A `cql` object. See [cql()].
#' @param file  Path to a file.
#'
#' @return Returns `cql` invisibly.
#' @export
write_oxcal <- function(cql, file) {
  checkmate::assert_class(cql, "cql")

  if(!stringr::str_ends(file, ".oxcal")) {
    file <- paste0(file, ".oxcal")
    message("Writing to ", file)
  }

  out <- utils::capture.output(print(cql))
  readr::write_lines(out, file, sep = "\r\n")

  invisible(cql)
}

# CQL commands ------------------------------------------------------------

#' @rdname cql
#' @export
cql_after <- function() { warning("CQL command After is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_age <- function() { warning("CQL command Age is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_axis <- function() { warning("CQL command Axis is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_before <- function() { warning("CQL command Before is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_boundary <- function(name, likelihood = NULL) {
  checkmate::assert_character(name)

  if(!is.null(likelihood)) {
    cql <- paste0("Boundary(\"", name, "\", ", likelihood, ");")
  }
  else {
    cql <- paste0("Boundary(\"", name, "\");")
  }
  cql <- cql(cql)
  return(cql)
}

#' @rdname cql
#' @export
cql_c_date <- function() { warning("CQL command C_Date is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_c_combine <- function() { warning("CQL command C_Combine is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_c_simulate <- function() { warning("CQL command C_Simulate is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_combine <- function() { warning("CQL command Combine is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_correl_matrix <- function() { warning("CQL command Correl_Matrix is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_correlation <- function() { warning("CQL command Correlation is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_covar_matrix <- function() { warning("CQL command Covar_Matrix is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_curve <- function() { warning("CQL command Curve is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_date <- function() { warning("CQL command Date is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_delta_r <- function() { warning("CQL command Delta_R is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_d_sequence <- function() { warning("CQL command D_Sequence is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_difference <- function() { warning("CQL command Difference is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_end <- function() { warning("CQL command End is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_exp <- function() { warning("CQL command Exp is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_first <- function() { warning("CQL command First is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_gap <- function() { warning("CQL command Gap is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_interval <- function() { warning("CQL command Interval is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_kde_model <- function() { warning("CQL command KDE_Model is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_kde_plot <- function() { warning("CQL command KDE_Plot is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_label <- function() { warning("CQL command Label is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_last <- function() { warning("CQL command Last is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_line <- function() { warning("CQL command Line is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_lnn <- function() { warning("CQL command LnN is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_mcmc_sample <- function() { warning("CQL command MCMC_Sample is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_mix_curves <- function() { warning("CQL command Mix_Curves is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_n <- function() { warning("CQL command N is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_number <- function() { warning("CQL command Number is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_order <- function() { warning("CQL command Order is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_offset <- function() { warning("CQL command Offset is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_outlier <- function() { warning("CQL command Outlier is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_outlier_model <- function() { warning("CQL command Outlier_Model is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_p <- function() { warning("CQL command P is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_p_sequence <- function() { warning("CQL command P_Sequence is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_phase <- function(name, ...) {
  checkmate::assert_character(name)
  assert_cql_dots(...)

  cql <- paste0("Phase(\"", name, "\")\n",
                "{\n",
                paste(..., sep = "\n"),
                "\n};")

  cql <- cql(cql)
  return(cql)
}

#' @rdname cql
#' @export
cql_pois <- function() { warning("CQL command Pois is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_prior <- function() { warning("CQL command Prior is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_probability <- function() { warning("CQL command Probability is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_r_date <- function(name, cra, error) {
  checkmate::assert_character(as.character(name))
  checkmate::assert_integerish(cra)
  checkmate::assert_integerish(error)

  if(length(name) != length(cra) |
     length(cra) != length(error) |
     length(error) != length(name)) {
    stop("Vector arguments to name, cra, error must all be the same length.")
  }

  cql <- paste0("R_Date(\"", name, "\", ", cra, ", ", error, ");")

  cql <- purrr::map(cql, stratigraphr::cql)
  return(cql)
}

#' @rdname cql
#' @export
cql_r_combine <- function() { warning("CQL command R_Combine is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_r_f14c <- function() { warning("CQL command R_F14C is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_r_simulate <- function() { warning("CQL command R_Simulate is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_reservoir <- function() { warning("CQL command Reservoir is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_sample <- function() { warning("CQL command Sample is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_sapwood <- function() { warning("CQL command Sapwood is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_sapwood_model <- function() { warning("CQL command Sapwood_Model is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_sequence <- function(name, ..., add_boundaries = FALSE) {
  checkmate::assert_character(name)
  checkmate::assert_logical(add_boundaries)
  assert_cql_dots(...)

  cql <- paste(..., sep = "\n")

  if(add_boundaries) {
    cql <- paste(cql_boundary(paste(name, "start")),
                 cql,
                 cql_boundary(paste(name, "end")),
                 sep = "\n")
  }

  cql <- paste(paste0("Sequence(\"", name, "\")"),
               "{",
               cql,
               "};",
               sep = "\n")

  cql <- cql(cql)
  return(cql)
}

#' @rdname cql
#' @export
cql_sigma_boundary <- function() { warning("CQL command Sigma_Boundary is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_shift <- function() { warning("CQL command Shift is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_span <- function() { warning("CQL command Span is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_start <- function() { warning("CQL command Start is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_sum <- function() { warning("CQL command Sum is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_t <- function() { warning("CQL command T is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_tau_boundary <- function() { warning("CQL command Tau_Boundary is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_top_hat <- function() { warning("CQL command Top_Hat is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_transition <- function() { warning("CQL command Transition is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_u <- function() { warning("CQL command U is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_u_sequence <- function() { warning("CQL command U_Sequence is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_v_sequence <- function() { warning("CQL command V_Sequence is not yet implemented in stratigraphr") }

#' @rdname cql
#' @export
cql_zero_boundary <- function() { warning("CQL command Zero_Boundary is not yet implemented in stratigraphr") }